# Generated by Django 4.2.29 on 2026-03-26 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('RESTORE', 'Restore'), ('TRANSFER', 'Transfer')], help_text='The type of action that was performed.', max_length=20)),
                ('model_name', models.CharField(help_text="Name of the affected model class (e.g., 'Chicken', 'Breeder').", max_length=100)),
                ('record_id', models.PositiveBigIntegerField(help_text='Primary key (ID) of the affected record.')),
                ('details', models.JSONField(blank=True, default=dict, help_text="Structured context about the action. e.g., {'wingband': 'WB-001', 'changed_fields': ['breeder']}.")),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this audit entry was created.')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Breeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. False means the record is deactivated, not removed.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of when this record was soft-deleted. NULL if still active.', null=True)),
                ('name', models.CharField(help_text='Full name of the breeder or farm/stable owner.', max_length=255)),
                ('location', models.CharField(help_text='City, municipality, province, or region the breeder is based in.', max_length=255)),
                ('contact', models.CharField(blank=True, help_text='Phone number or email address (optional but recommended).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Breeder',
                'verbose_name_plural': 'Breeders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. False means the record is deactivated, not removed.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of when this record was soft-deleted. NULL if still active.', null=True)),
                ('wingband_number', models.CharField(db_index=True, help_text='Unique wingband identifier (primary lookup key). Cannot be reused while this record exists (even if soft-deleted).', max_length=50, unique=True)),
                ('color', models.CharField(choices=[('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('PYLE', 'Pyle'), ('SPANGLED', 'Spangled'), ('DARK_RED', 'Dark Red'), ('MIXED', 'Mixed'), ('OTHER', 'Other')], help_text='Primary feather color of the gamefowl.', max_length=20)),
                ('comb_type', models.CharField(choices=[('SINGLE', 'Single'), ('DUPLEX', 'Duplex'), ('STRAWBERRY', 'Strawberry'), ('WALNUT', 'Walnut'), ('PEA', 'Pea'), ('CUSHION', 'Cushion'), ('ROSE', 'Rose')], help_text='Physical comb type of the gamefowl.', max_length=20)),
                ('leg_color', models.CharField(choices=[('YELLOW', 'Yellow'), ('WHITE', 'White'), ('WILLOW', 'Willow'), ('BLACK', 'Black'), ('BLUE', 'Blue'), ('MIXED', 'Mixed')], help_text='Shank (leg) color of the gamefowl.', max_length=20)),
                ('birth_category', models.CharField(choices=[('EARLY_BIRD', 'Early Bird'), ('LOCAL', 'Local'), ('NATIONAL', 'National'), ('LATE_BORN', 'Late Born')], help_text='Permanent birth-period tier assigned at registration. This field MUST NOT be changed after the record is created.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this chicken was first registered in the system.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breeder', models.ForeignKey(help_text='The registered breeder this chicken is assigned to.', on_delete=django.db.models.deletion.PROTECT, related_name='chickens', to='registry.breeder')),
            ],
            options={
                'verbose_name': 'Chicken',
                'verbose_name_plural': 'Chickens',
                'ordering': ['wingband_number'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(help_text='Full name of the new owner (required). Auto-populate from owner_breeder.name if the FK is provided.', max_length=255)),
                ('date_transferred', models.DateField(help_text='Actual date the ownership transfer took place. Can be backdated.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='System timestamp of when this record was entered. Auto-set, not editable.')),
                ('notes', models.TextField(blank=True, help_text='Optional context about the transfer (e.g., event name, derby, reason).')),
                ('chicken', models.ForeignKey(help_text='The chicken involved in this ownership transfer.', on_delete=django.db.models.deletion.PROTECT, related_name='ownership_history', to='registry.chicken')),
                ('owner_breeder', models.ForeignKey(blank=True, help_text='Link to the registered Breeder who received this chicken (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_chickens', to='registry.breeder')),
            ],
            options={
                'verbose_name': 'Ownership History',
                'verbose_name_plural': 'Ownership Histories',
                'ordering': ['-date_transferred', '-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='breeder',
            index=models.Index(fields=['name'], name='breeder_name_idx'),
        ),
        migrations.AddIndex(
            model_name='breeder',
            index=models.Index(fields=['is_active'], name='breeder_active_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The admin user who triggered this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ownershiphistory',
            index=models.Index(fields=['chicken', 'date_transferred'], name='ownership_chicken_date_idx'),
        ),
        migrations.AddIndex(
            model_name='chicken',
            index=models.Index(fields=['breeder', 'is_active'], name='chicken_breeder_active_idx'),
        ),
        migrations.AddIndex(
            model_name='chicken',
            index=models.Index(fields=['birth_category'], name='chicken_birth_category_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'record_id'], name='auditlog_model_record_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='auditlog_user_time_idx'),
        ),
    ]
